// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  const env = globalThis.process?.env ?? {};
  return createClient(
    env.SUPABASE_URL,
    env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var unauthenticated = {
  content: [{ type: "text", text: "Not authenticated" }],
  isError: true
};
var errorResult = (message) => ({
  content: [{ type: "text", text: message }],
  isError: true
});
var jsonResult = (data) => ({
  content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
  structuredContent: { data }
});

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's profile: role (student, institute or company), name, APAAR ID, institute/company name and account status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated;
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "role, full_name, phone, appar_id, institute_name, company_name, website, address, status"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("No profile found for this account.");
    return jsonResult({ ...data, email: ctx.getUserEmail() });
  }
});

// src/lib/mcp/tools/list-my-credentials.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";
var list_my_credentials_default = defineTool2({
  name: "list_my_credentials",
  title: "List my credentials",
  description: "List academic credentials visible to the signed-in user. Students see credentials issued to them; institutes see credentials they issued.",
  inputSchema: {
    limit: z.number().int().describe("Maximum number of credentials to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated;
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("credentials").select(
      "id, title, description, credential_type, issuer_name, student_full_name, student_appar_id, student_roll_number, issued_date, expiry_date, verification_status"
    ).order("issued_date", { ascending: false }).limit(take);
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, credentials: data ?? [] });
  }
});

// src/lib/mcp/tools/get-credential.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_credential_default = defineTool3({
  name: "get_credential",
  title: "Get credential details",
  description: "Fetch the full details of one credential by its ID, including verification status. Only credentials the signed-in user may access are returned.",
  inputSchema: {
    credential_id: z2.string().describe("The UUID of the credential.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ credential_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated;
    const { data, error } = await supabaseForUser(ctx).from("credentials").select(
      "id, title, description, credential_type, issuer_name, student_full_name, student_email, student_appar_id, student_roll_number, issued_date, expiry_date, verification_status, metadata, created_at"
    ).eq("id", credential_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Credential not found or not accessible.");
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-credential-requests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_credential_requests_default = defineTool4({
  name: "list_credential_requests",
  title: "List credential requests",
  description: "List credential issuance requests visible to the signed-in user. Students see their own requests; institutes see requests addressed to them.",
  inputSchema: {
    status: z3.string().describe("Optional status filter, e.g. pending, approved or rejected.").optional(),
    limit: z3.number().int().describe("Maximum number of requests to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated;
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("credential_requests").select(
      "id, title, credential_type, description, student_full_name, student_appar_id, student_roll_number, status, rejection_reason, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, requests: data ?? [] });
  }
});

// src/lib/mcp/tools/create-credential-request.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_credential_request_default = defineTool5({
  name: "create_credential_request",
  title: "Request a credential",
  description: "Create a credential issuance request from the signed-in student to an institute. The institute reviews and approves it in the app.",
  inputSchema: {
    issuer_id: z4.string().describe("User ID of the institute the request is sent to."),
    title: z4.string().describe("Title of the requested credential, e.g. 'B.Tech Degree Certificate'."),
    credential_type: z4.string().describe("Type of credential, e.g. degree, diploma, certificate."),
    description: z4.string().describe("Why the credential is needed.").optional(),
    roll_number: z4.string().describe("The student's roll number at the institute.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("profiles").select("role, full_name, phone, appar_id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (profileError) return errorResult(profileError.message);
    if (!profile) return errorResult("No profile found for this account.");
    if (profile.role !== "student") return errorResult("Only students can request credentials.");
    const { data, error } = await supabase.from("credential_requests").insert({
      student_id: ctx.getUserId(),
      issuer_id: input.issuer_id,
      title: input.title,
      credential_type: input.credential_type,
      description: input.description ?? null,
      student_full_name: profile.full_name,
      student_email: ctx.getUserEmail() ?? null,
      student_appar_id: profile.appar_id,
      student_phone: profile.phone,
      student_roll_number: input.roll_number ?? null
    }).select("id, title, status, created_at").maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-institutes.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_institutes_default = defineTool6({
  name: "list_institutes",
  title: "List institutes",
  description: "List institutes registered on the platform, with their user IDs \u2014 use these IDs as issuer_id when creating a credential request.",
  inputSchema: {
    search: z5.string().describe("Optional case-insensitive name filter.").optional(),
    limit: z5.number().int().describe("Maximum number of institutes to return (default 25).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated;
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("profiles").select("user_id, institute_name, website, address").eq("role", "institute").limit(take);
    if (search) query = query.ilike("institute_name", `%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, institutes: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "jrchdzojqwjvnyzddqwc";
var mcp_default = defineMcp({
  name: "origincerti-mcp",
  title: "OriginCerti Credentials",
  version: "0.1.0",
  instructions: "Tools for OriginCerti, a digital academic credentials platform (students, institutes and companies). Use `get_my_profile` to learn the signed-in user's role, `list_my_credentials` and `get_credential` to read issued credentials, `list_institutes` to find an institute's issuer_id, and `list_credential_requests` / `create_credential_request` to track or raise credential issuance requests. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_my_credentials_default,
    get_credential_default,
    list_credential_requests_default,
    create_credential_request_default,
    list_institutes_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
